Implement multi-licensed items
citation-file-format/citation-file-format pull request #157
Opened 2021-05-17 14:00 UTC by sdruskat

This PR is against `1.2.0`!

**Related issues**

Refs: 
- fix #128 
- Doesn't supply a fix for #105

**Describe the changes made in this pull request**

- Move license enums to "private" definition `#/definitions/_license-enum`
- Re-define `#/definitions/license` to be `oneOf` `_license_enum` or an array pf `_license-enum`.
- Add test data to test both cases

**Instructions to review the pull request**

```bash
git clone this repo
git checkout this branch
python3 -m venv env
source env/bin/activate
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
python3 schema_poc.py -d data.yml -s schema.json  # <- should be quiet
```

2021-05-17 18:18 UTC, jspaaks requested changes
I would prefer to not have the leading underscore to suggest privateness, other than that it's good to go

2021-05-18 10:26 UTC, sdruskat commented
Thanks for the review. Removed the leading underscore as suggested in https://github.com/citation-file-format/citation-file-format/pull/157/commits/5ea9231f8ca7ddb5e1836f5dc811e68224f76a5a.

2021-05-18 11:06 UTC, jspaaks approved these changes
Good to merge!

2021-05-18 11:11 UTC, merged

2021-05-18 11:11 UTC, sdruskat commented
Thanks for the 2nd review as well!